// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.19.4
// source: pb/sys.proto

package sys

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_pb_sys_proto protoreflect.FileDescriptor

const file_pb_sys_proto_rawDesc = "" +
	"\n" +
	"\fpb/sys.proto\x12\x03sys\x1a\x0fpb/common.proto\x1a\rpb/auth.proto2-\n" +
	"\x03Sys\x12&\n" +
	"\x05Login\x12\r.sys.LoginReq\x1a\x0e.sys.LoginRespB\aZ\x05./sysb\x06proto3"

var file_pb_sys_proto_goTypes = []any{
	(*LoginReq)(nil),  // 0: sys.LoginReq
	(*LoginResp)(nil), // 1: sys.LoginResp
}
var file_pb_sys_proto_depIdxs = []int32{
	0, // 0: sys.Sys.Login:input_type -> sys.LoginReq
	1, // 1: sys.Sys.Login:output_type -> sys.LoginResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_sys_proto_init() }
func file_pb_sys_proto_init() {
	if File_pb_sys_proto != nil {
		return
	}
	file_pb_common_proto_init()
	file_pb_auth_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_sys_proto_rawDesc), len(file_pb_sys_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_sys_proto_goTypes,
		DependencyIndexes: file_pb_sys_proto_depIdxs,
	}.Build()
	File_pb_sys_proto = out.File
	file_pb_sys_proto_goTypes = nil
	file_pb_sys_proto_depIdxs = nil
}
