// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: sys.proto

package server

import (
	"context"

	"go-zero-rpc/sys-rpc/internal/logic/systemservice"
	"go-zero-rpc/sys-rpc/internal/svc"
	"go-zero-rpc/sys-rpc/sys"
)

type SystemServiceServer struct {
	svcCtx *svc.ServiceContext
	sys.UnimplementedSystemServiceServer
}

func NewSystemServiceServer(svcCtx *svc.ServiceContext) *SystemServiceServer {
	return &SystemServiceServer{
		svcCtx: svcCtx,
	}
}

// 用户管理
func (s *SystemServiceServer) CreateUser(ctx context.Context, in *sys.CreateUserReq) (*sys.CreateUserResp, error) {
	l := systemservicelogic.NewCreateUserLogic(ctx, s.svcCtx)
	return l.CreateUser(in)
}

func (s *SystemServiceServer) UpdateUser(ctx context.Context, in *sys.UpdateUserReq) (*sys.Empty, error) {
	l := systemservicelogic.NewUpdateUserLogic(ctx, s.svcCtx)
	return l.UpdateUser(in)
}

func (s *SystemServiceServer) DeleteUser(ctx context.Context, in *sys.DeleteUserReq) (*sys.Empty, error) {
	l := systemservicelogic.NewDeleteUserLogic(ctx, s.svcCtx)
	return l.DeleteUser(in)
}

func (s *SystemServiceServer) GetUser(ctx context.Context, in *sys.GetUserReq) (*sys.UserItem, error) {
	l := systemservicelogic.NewGetUserLogic(ctx, s.svcCtx)
	return l.GetUser(in)
}

func (s *SystemServiceServer) ListUser(ctx context.Context, in *sys.ListUserReq) (*sys.ListUserResp, error) {
	l := systemservicelogic.NewListUserLogic(ctx, s.svcCtx)
	return l.ListUser(in)
}

func (s *SystemServiceServer) ResetPassword(ctx context.Context, in *sys.ResetPasswordReq) (*sys.Empty, error) {
	l := systemservicelogic.NewResetPasswordLogic(ctx, s.svcCtx)
	return l.ResetPassword(in)
}
