// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: sys.proto

package server

import (
	"context"

	"go-zero-rpc/sys-rpc/internal/logic/permissionservice"
	"go-zero-rpc/sys-rpc/internal/svc"
	"go-zero-rpc/sys-rpc/sys"
)

type PermissionServiceServer struct {
	svcCtx *svc.ServiceContext
	sys.UnimplementedPermissionServiceServer
}

func NewPermissionServiceServer(svcCtx *svc.ServiceContext) *PermissionServiceServer {
	return &PermissionServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *PermissionServiceServer) CheckPermission(ctx context.Context, in *sys.CheckPermissionReq) (*sys.CheckPermissionResp, error) {
	l := permissionservicelogic.NewCheckPermissionLogic(ctx, s.svcCtx)
	return l.CheckPermission(in)
}

func (s *PermissionServiceServer) GetUserById(ctx context.Context, in *sys.GetUserByIdReq) (*sys.GetUserByIdResp, error) {
	l := permissionservicelogic.NewGetUserByIdLogic(ctx, s.svcCtx)
	return l.GetUserById(in)
}

func (s *PermissionServiceServer) GetRolesByUserId(ctx context.Context, in *sys.GetRolesByUserIdReq) (*sys.GetRolesByUserIdResp, error) {
	l := permissionservicelogic.NewGetRolesByUserIdLogic(ctx, s.svcCtx)
	return l.GetRolesByUserId(in)
}

func (s *PermissionServiceServer) IsTokenRevoked(ctx context.Context, in *sys.IsBlackListReq) (*sys.IsBlackListResp, error) {
	l := permissionservicelogic.NewIsTokenRevokedLogic(ctx, s.svcCtx)
	return l.IsTokenRevoked(in)
}
