// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	sysFileFieldNames          = builder.RawFieldNames(&SysFile{}, true)
	sysFileRows                = strings.Join(sysFileFieldNames, ",")
	sysFileRowsExpectAutoSet   = strings.Join(stringx.Remove(sysFileFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	sysFileRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(sysFileFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	sysFileModel interface {
		Insert(ctx context.Context, data *SysFile) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*SysFile, error)
		Update(ctx context.Context, data *SysFile) error
		Delete(ctx context.Context, id int64) error
	}

	defaultSysFileModel struct {
		conn  sqlx.SqlConn
		table string
	}

	SysFile struct {
		Id         int64        `db:"id"`          // 文件ID
		Filename   string       `db:"filename"`    // 存储文件名（UUID生成）
		OriginName string       `db:"origin_name"` // 原始文件名
		FilePath   string       `db:"file_path"`   // 文件存储路径
		FileUrl    string       `db:"file_url"`    // 文件访问URL
		FileSize   int64        `db:"file_size"`   // 文件大小（字节）
		FileType   string       `db:"file_type"`   // 文件类型/MIME类型
		UploaderId int64        `db:"uploader_id"` // 上传人用户ID
		CreatedAt  time.Time    `db:"created_at"`  // 上传时间
		DeletedAt  sql.NullTime `db:"deleted_at"`  // 软删除时间, 空-未删除，非空为已删除时间
	}
)

func newSysFileModel(conn sqlx.SqlConn) *defaultSysFileModel {
	return &defaultSysFileModel{
		conn:  conn,
		table: `"public"."sys_file"`,
	}
}

func (m *defaultSysFileModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultSysFileModel) FindOne(ctx context.Context, id int64) (*SysFile, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", sysFileRows, m.table)
	var resp SysFile
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSysFileModel) Insert(ctx context.Context, data *SysFile) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6, $7, $8)", m.table, sysFileRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Filename, data.OriginName, data.FilePath, data.FileUrl, data.FileSize, data.FileType, data.UploaderId, data.DeletedAt)
	return ret, err
}

func (m *defaultSysFileModel) Update(ctx context.Context, data *SysFile) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, sysFileRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Id, data.Filename, data.OriginName, data.FilePath, data.FileUrl, data.FileSize, data.FileType, data.UploaderId, data.DeletedAt)
	return err
}

func (m *defaultSysFileModel) tableName() string {
	return m.table
}
