// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	sysRoleApiFieldNames          = builder.RawFieldNames(&SysRoleApi{})
	sysRoleApiRows                = strings.Join(sysRoleApiFieldNames, ",")
	sysRoleApiRowsExpectAutoSet   = strings.Join(stringx.Remove(sysRoleApiFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	sysRoleApiRowsWithPlaceHolder = strings.Join(stringx.Remove(sysRoleApiFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	sysRoleApiModel interface {
		Insert(ctx context.Context, data *SysRoleApi) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*SysRoleApi, error)
		FindOneByRoleIdApiId(ctx context.Context, roleId int64, apiId int64) (*SysRoleApi, error)
		Update(ctx context.Context, data *SysRoleApi) error
		Delete(ctx context.Context, id int64) error
	}

	defaultSysRoleApiModel struct {
		conn  sqlx.SqlConn
		table string
	}

	SysRoleApi struct {
		Id     int64 `db:"id"`      // 主键ID
		RoleId int64 `db:"role_id"` // 角色ID
		ApiId  int64 `db:"api_id"`  // 接口ID
	}
)

func newSysRoleApiModel(conn sqlx.SqlConn) *defaultSysRoleApiModel {
	return &defaultSysRoleApiModel{
		conn:  conn,
		table: "`sys_role_api`",
	}
}

func (m *defaultSysRoleApiModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultSysRoleApiModel) FindOne(ctx context.Context, id int64) (*SysRoleApi, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", sysRoleApiRows, m.table)
	var resp SysRoleApi
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSysRoleApiModel) FindOneByRoleIdApiId(ctx context.Context, roleId int64, apiId int64) (*SysRoleApi, error) {
	var resp SysRoleApi
	query := fmt.Sprintf("select %s from %s where `role_id` = ? and `api_id` = ? limit 1", sysRoleApiRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, roleId, apiId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSysRoleApiModel) Insert(ctx context.Context, data *SysRoleApi) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?)", m.table, sysRoleApiRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.RoleId, data.ApiId)
	return ret, err
}

func (m *defaultSysRoleApiModel) Update(ctx context.Context, newData *SysRoleApi) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, sysRoleApiRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.RoleId, newData.ApiId, newData.Id)
	return err
}

func (m *defaultSysRoleApiModel) tableName() string {
	return m.table
}
