// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	sysApiFieldNames          = builder.RawFieldNames(&SysApi{}, true)
	sysApiRows                = strings.Join(sysApiFieldNames, ",")
	sysApiRowsExpectAutoSet   = strings.Join(stringx.Remove(sysApiFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	sysApiRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(sysApiFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	sysApiModel interface {
		Insert(ctx context.Context, data *SysApi) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*SysApi, error)
		FindOneByApiPathMethod(ctx context.Context, apiPath string, method string) (*SysApi, error)
		Update(ctx context.Context, data *SysApi) error
		Delete(ctx context.Context, id int64) error
	}

	defaultSysApiModel struct {
		conn  sqlx.SqlConn
		table string
	}

	SysApi struct {
		Id          int64        `db:"id"`          // 接口ID
		ApiPath     string       `db:"api_path"`    // 接口路径，如：/api/system/user
		Method      string       `db:"method"`      // HTTP方法：GET/POST/PUT/DELETE
		ApiGroup    string       `db:"api_group"`   // 接口分组，如：系统管理
		Description string       `db:"description"` // 接口描述
		CreatedAt   time.Time    `db:"created_at"`  // 创建时间
		UpdatedAt   time.Time    `db:"updated_at"`  // 更新时间
		DeletedAt   sql.NullTime `db:"deleted_at"`  // 软删除时间, 空-未删除，非空为已删除时间
		ApiName     string       `db:"api_name"`    // 接口中文名称
	}
)

func newSysApiModel(conn sqlx.SqlConn) *defaultSysApiModel {
	return &defaultSysApiModel{
		conn:  conn,
		table: `"public"."sys_api"`,
	}
}

func (m *defaultSysApiModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultSysApiModel) FindOne(ctx context.Context, id int64) (*SysApi, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", sysApiRows, m.table)
	var resp SysApi
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSysApiModel) FindOneByApiPathMethod(ctx context.Context, apiPath string, method string) (*SysApi, error) {
	var resp SysApi
	query := fmt.Sprintf("select %s from %s where api_path = $1 and method = $2 limit 1", sysApiRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, apiPath, method)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSysApiModel) Insert(ctx context.Context, data *SysApi) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6)", m.table, sysApiRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.ApiPath, data.Method, data.ApiGroup, data.Description, data.DeletedAt, data.ApiName)
	return ret, err
}

func (m *defaultSysApiModel) Update(ctx context.Context, newData *SysApi) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, sysApiRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Id, newData.ApiPath, newData.Method, newData.ApiGroup, newData.Description, newData.DeletedAt, newData.ApiName)
	return err
}

func (m *defaultSysApiModel) tableName() string {
	return m.table
}
