// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	sysDictDataFieldNames          = builder.RawFieldNames(&SysDictData{})
	sysDictDataRows                = strings.Join(sysDictDataFieldNames, ",")
	sysDictDataRowsExpectAutoSet   = strings.Join(stringx.Remove(sysDictDataFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	sysDictDataRowsWithPlaceHolder = strings.Join(stringx.Remove(sysDictDataFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	sysDictDataModel interface {
		Insert(ctx context.Context, data *SysDictData) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*SysDictData, error)
		Update(ctx context.Context, data *SysDictData) error
		Delete(ctx context.Context, id int64) error
	}

	defaultSysDictDataModel struct {
		conn  sqlx.SqlConn
		table string
	}

	SysDictData struct {
		Id        int64        `db:"id"`         // 字典数据ID
		TypeId    int64        `db:"type_id"`    // 字典类型ID
		Label     string       `db:"label"`      // 字典标签（显示名称）
		DictValue string       `db:"dict_value"` // 字典键值
		Sort      int64        `db:"sort"`       // 排序值
		Status    int64        `db:"status"`     // 状态：1=启用，0=禁用
		Remark    string       `db:"remark"`     // 备注
		CreatedAt time.Time    `db:"created_at"` // 创建时间
		UpdatedAt time.Time    `db:"updated_at"` // 更新时间
		DeletedAt sql.NullTime `db:"deleted_at"` // 软删除时间, 空-未删除，非空为已删除时间
	}
)

func newSysDictDataModel(conn sqlx.SqlConn) *defaultSysDictDataModel {
	return &defaultSysDictDataModel{
		conn:  conn,
		table: "`sys_dict_data`",
	}
}

func (m *defaultSysDictDataModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultSysDictDataModel) FindOne(ctx context.Context, id int64) (*SysDictData, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", sysDictDataRows, m.table)
	var resp SysDictData
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSysDictDataModel) Insert(ctx context.Context, data *SysDictData) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, sysDictDataRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.TypeId, data.Label, data.DictValue, data.Sort, data.Status, data.Remark, data.DeletedAt)
	return ret, err
}

func (m *defaultSysDictDataModel) Update(ctx context.Context, data *SysDictData) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, sysDictDataRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.TypeId, data.Label, data.DictValue, data.Sort, data.Status, data.Remark, data.DeletedAt, data.Id)
	return err
}

func (m *defaultSysDictDataModel) tableName() string {
	return m.table
}
