// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	sysLoginLogFieldNames          = builder.RawFieldNames(&SysLoginLog{}, true)
	sysLoginLogRows                = strings.Join(sysLoginLogFieldNames, ",")
	sysLoginLogRowsExpectAutoSet   = strings.Join(stringx.Remove(sysLoginLogFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	sysLoginLogRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(sysLoginLogFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	sysLoginLogModel interface {
		Insert(ctx context.Context, data *SysLoginLog) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*SysLoginLog, error)
		Update(ctx context.Context, data *SysLoginLog) error
		Delete(ctx context.Context, id int64) error
	}

	defaultSysLoginLogModel struct {
		conn  sqlx.SqlConn
		table string
	}

	SysLoginLog struct {
		Id        int64        `db:"id"`         // 日志ID
		UserId    int64        `db:"user_id"`    // 用户ID
		Username  string       `db:"username"`   // 用户名
		Ip        string       `db:"ip"`         // 登录IP
		Location  string       `db:"location"`   // 登录地点
		Browser   string       `db:"browser"`    // 浏览器
		Os        string       `db:"os"`         // 操作系统
		Status    int64        `db:"status"`     // 登录状态：1=成功，0=失败
		Msg       string       `db:"msg"`        // 提示消息
		LoginTime time.Time    `db:"login_time"` // 登录时间
		DeletedAt sql.NullTime `db:"deleted_at"` // 软删除时间, 空-未删除，非空为已删除时间
	}
)

func newSysLoginLogModel(conn sqlx.SqlConn) *defaultSysLoginLogModel {
	return &defaultSysLoginLogModel{
		conn:  conn,
		table: `"public"."sys_login_log"`,
	}
}

func (m *defaultSysLoginLogModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultSysLoginLogModel) FindOne(ctx context.Context, id int64) (*SysLoginLog, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", sysLoginLogRows, m.table)
	var resp SysLoginLog
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSysLoginLogModel) Insert(ctx context.Context, data *SysLoginLog) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)", m.table, sysLoginLogRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.Username, data.Ip, data.Location, data.Browser, data.Os, data.Status, data.Msg, data.LoginTime, data.DeletedAt)
	return ret, err
}

func (m *defaultSysLoginLogModel) Update(ctx context.Context, data *SysLoginLog) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, sysLoginLogRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Id, data.UserId, data.Username, data.Ip, data.Location, data.Browser, data.Os, data.Status, data.Msg, data.LoginTime, data.DeletedAt)
	return err
}

func (m *defaultSysLoginLogModel) tableName() string {
	return m.table
}
