// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	sysRoleFieldNames          = builder.RawFieldNames(&SysRole{}, true)
	sysRoleRows                = strings.Join(sysRoleFieldNames, ",")
	sysRoleRowsExpectAutoSet   = strings.Join(stringx.Remove(sysRoleFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	sysRoleRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(sysRoleFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	sysRoleModel interface {
		Insert(ctx context.Context, data *SysRole) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*SysRole, error)
		FindOneByCode(ctx context.Context, code string) (*SysRole, error)
		Update(ctx context.Context, data *SysRole) error
		Delete(ctx context.Context, id int64) error
	}

	defaultSysRoleModel struct {
		conn  sqlx.SqlConn
		table string
	}

	SysRole struct {
		Id        int64        `db:"id"`         // 角色ID
		Name      string       `db:"name"`       // 角色名称
		Code      string       `db:"code"`       // 角色编码（casbin中使用）
		Status    int64        `db:"status"`     // 状态：1=启用，0=禁用
		Remark    string       `db:"remark"`     // 备注
		Sort      int64        `db:"sort"`       // 排序值，越小越靠前
		CreatedAt time.Time    `db:"created_at"` // 创建时间
		UpdatedAt time.Time    `db:"updated_at"` // 更新时间
		DeletedAt sql.NullTime `db:"deleted_at"` // 软删除时间, 空-未删除，非空为已删除时间
	}
)

func newSysRoleModel(conn sqlx.SqlConn) *defaultSysRoleModel {
	return &defaultSysRoleModel{
		conn:  conn,
		table: `"public"."sys_role"`,
	}
}

func (m *defaultSysRoleModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultSysRoleModel) FindOne(ctx context.Context, id int64) (*SysRole, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", sysRoleRows, m.table)
	var resp SysRole
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSysRoleModel) FindOneByCode(ctx context.Context, code string) (*SysRole, error) {
	var resp SysRole
	query := fmt.Sprintf("select %s from %s where code = $1 limit 1", sysRoleRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, code)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSysRoleModel) Insert(ctx context.Context, data *SysRole) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6)", m.table, sysRoleRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Name, data.Code, data.Status, data.Remark, data.Sort, data.DeletedAt)
	return ret, err
}

func (m *defaultSysRoleModel) Update(ctx context.Context, newData *SysRole) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, sysRoleRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Id, newData.Name, newData.Code, newData.Status, newData.Remark, newData.Sort, newData.DeletedAt)
	return err
}

func (m *defaultSysRoleModel) tableName() string {
	return m.table
}
