// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	sysDictTypeFieldNames          = builder.RawFieldNames(&SysDictType{}, true)
	sysDictTypeRows                = strings.Join(sysDictTypeFieldNames, ",")
	sysDictTypeRowsExpectAutoSet   = strings.Join(stringx.Remove(sysDictTypeFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	sysDictTypeRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(sysDictTypeFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	sysDictTypeModel interface {
		Insert(ctx context.Context, data *SysDictType) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*SysDictType, error)
		FindOneByCode(ctx context.Context, code string) (*SysDictType, error)
		Update(ctx context.Context, data *SysDictType) error
		Delete(ctx context.Context, id int64) error
	}

	defaultSysDictTypeModel struct {
		conn  sqlx.SqlConn
		table string
	}

	SysDictType struct {
		Id        int64        `db:"id"`         // 字典类型ID
		Name      string       `db:"name"`       // 字典类型名称
		Code      string       `db:"code"`       // 字典类型编码
		Status    int64        `db:"status"`     // 状态：1=启用，0=禁用
		Remark    string       `db:"remark"`     // 备注
		CreatedAt time.Time    `db:"created_at"` // 创建时间
		UpdatedAt time.Time    `db:"updated_at"` // 更新时间
		DeletedAt sql.NullTime `db:"deleted_at"` // 软删除时间, 空-未删除，非空为已删除时间
	}
)

func newSysDictTypeModel(conn sqlx.SqlConn) *defaultSysDictTypeModel {
	return &defaultSysDictTypeModel{
		conn:  conn,
		table: `"public"."sys_dict_type"`,
	}
}

func (m *defaultSysDictTypeModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultSysDictTypeModel) FindOne(ctx context.Context, id int64) (*SysDictType, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", sysDictTypeRows, m.table)
	var resp SysDictType
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSysDictTypeModel) FindOneByCode(ctx context.Context, code string) (*SysDictType, error) {
	var resp SysDictType
	query := fmt.Sprintf("select %s from %s where code = $1 limit 1", sysDictTypeRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, code)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSysDictTypeModel) Insert(ctx context.Context, data *SysDictType) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5)", m.table, sysDictTypeRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Name, data.Code, data.Status, data.Remark, data.DeletedAt)
	return ret, err
}

func (m *defaultSysDictTypeModel) Update(ctx context.Context, newData *SysDictType) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, sysDictTypeRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Id, newData.Name, newData.Code, newData.Status, newData.Remark, newData.DeletedAt)
	return err
}

func (m *defaultSysDictTypeModel) tableName() string {
	return m.table
}
