// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	sysRoleMenuFieldNames          = builder.RawFieldNames(&SysRoleMenu{}, true)
	sysRoleMenuRows                = strings.Join(sysRoleMenuFieldNames, ",")
	sysRoleMenuRowsExpectAutoSet   = strings.Join(stringx.Remove(sysRoleMenuFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	sysRoleMenuRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(sysRoleMenuFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	sysRoleMenuModel interface {
		Insert(ctx context.Context, data *SysRoleMenu) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*SysRoleMenu, error)
		FindOneByRoleIdMenuId(ctx context.Context, roleId int64, menuId int64) (*SysRoleMenu, error)
		Update(ctx context.Context, data *SysRoleMenu) error
		Delete(ctx context.Context, id int64) error
	}

	defaultSysRoleMenuModel struct {
		conn  sqlx.SqlConn
		table string
	}

	SysRoleMenu struct {
		Id     int64 `db:"id"`      // 主键ID
		RoleId int64 `db:"role_id"` // 角色ID
		MenuId int64 `db:"menu_id"` // 菜单ID
	}
)

func newSysRoleMenuModel(conn sqlx.SqlConn) *defaultSysRoleMenuModel {
	return &defaultSysRoleMenuModel{
		conn:  conn,
		table: `"public"."sys_role_menu"`,
	}
}

func (m *defaultSysRoleMenuModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultSysRoleMenuModel) FindOne(ctx context.Context, id int64) (*SysRoleMenu, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", sysRoleMenuRows, m.table)
	var resp SysRoleMenu
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSysRoleMenuModel) FindOneByRoleIdMenuId(ctx context.Context, roleId int64, menuId int64) (*SysRoleMenu, error) {
	var resp SysRoleMenu
	query := fmt.Sprintf("select %s from %s where role_id = $1 and menu_id = $2 limit 1", sysRoleMenuRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, roleId, menuId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSysRoleMenuModel) Insert(ctx context.Context, data *SysRoleMenu) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2)", m.table, sysRoleMenuRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.RoleId, data.MenuId)
	return ret, err
}

func (m *defaultSysRoleMenuModel) Update(ctx context.Context, newData *SysRoleMenu) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, sysRoleMenuRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Id, newData.RoleId, newData.MenuId)
	return err
}

func (m *defaultSysRoleMenuModel) tableName() string {
	return m.table
}
