// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	auth "go-zero-rpc/gateway/internal/handler/auth"
	sysapi "go-zero-rpc/gateway/internal/handler/sys/api"
	syscasbin "go-zero-rpc/gateway/internal/handler/sys/casbin"
	sysdict "go-zero-rpc/gateway/internal/handler/sys/dict"
	sysfile "go-zero-rpc/gateway/internal/handler/sys/file"
	syslog "go-zero-rpc/gateway/internal/handler/sys/log"
	sysmenu "go-zero-rpc/gateway/internal/handler/sys/menu"
	sysrole "go-zero-rpc/gateway/internal/handler/sys/role"
	sysuser "go-zero-rpc/gateway/internal/handler/sys/user"
	"go-zero-rpc/gateway/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: auth.LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/refresh",
				Handler: auth.RefreshTokenHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/auth"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/changePassword",
					Handler: auth.ChangePasswordHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/logout",
					Handler: auth.LogoutHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/userInfo",
					Handler: auth.GetCurrentUserHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/auth"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware, serverCtx.CasbinMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/api",
					Handler: sysapi.CreateApiHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api",
					Handler: sysapi.ListApiHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/:id",
					Handler: sysapi.UpdateApiHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/api/:id",
					Handler: sysapi.DeleteApiHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/all",
					Handler: sysapi.ListAllApiHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/system"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware, serverCtx.CasbinMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/casbin/rules",
					Handler: syscasbin.ListCasbinRuleHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/system"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware, serverCtx.CasbinMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/dict/data",
					Handler: sysdict.CreateDictDataHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/dict/data/:dictType",
					Handler: sysdict.GetDictDataByTypeHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/dict/data/:id",
					Handler: sysdict.UpdateDictDataHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/dict/data/:id",
					Handler: sysdict.DeleteDictDataHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/dict/type",
					Handler: sysdict.CreateDictTypeHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/dict/type",
					Handler: sysdict.ListDictTypeHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/dict/type/:id",
					Handler: sysdict.UpdateDictTypeHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/dict/type/:id",
					Handler: sysdict.DeleteDictTypeHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/system"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware, serverCtx.CasbinMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/file",
					Handler: sysfile.ListFileHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/file/:id",
					Handler: sysfile.DeleteFileHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/file/upload",
					Handler: sysfile.UploadFileHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/system"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware, serverCtx.CasbinMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/log/login",
					Handler: syslog.ListLoginLogHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/log/login/clear",
					Handler: syslog.ClearLoginLogHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/log/oper",
					Handler: syslog.ListOperLogHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/log/oper/clear",
					Handler: syslog.ClearOperLogHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/system"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware, serverCtx.CasbinMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/menu",
					Handler: sysmenu.CreateMenuHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/menu/:id",
					Handler: sysmenu.UpdateMenuHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/menu/:id",
					Handler: sysmenu.DeleteMenuHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/menu/current",
					Handler: sysmenu.GetCurrentUserMenusHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/menu/tree",
					Handler: sysmenu.GetMenuTreeHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/system"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware, serverCtx.CasbinMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/role",
					Handler: sysrole.CreateRoleHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/role",
					Handler: sysrole.ListRoleHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/role/:id",
					Handler: sysrole.UpdateRoleHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/role/:id",
					Handler: sysrole.DeleteRoleHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/role/:id",
					Handler: sysrole.GetRoleHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/role/:id/permissions",
					Handler: sysrole.UpdateRolePermissionsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/role/all",
					Handler: sysrole.ListAllRoleHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/system"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware, serverCtx.CasbinMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/user",
					Handler: sysuser.CreateUserHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/user",
					Handler: sysuser.ListUserHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/user/:id",
					Handler: sysuser.UpdateUserHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/user/:id",
					Handler: sysuser.DeleteUserHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/user/:id",
					Handler: sysuser.GetUserHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/user/:id/reset-password",
					Handler: sysuser.ResetPasswordHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/system"),
	)
}
