// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	AccessToken  string   `json:"accessToken"`
	RefreshToken string   `json:"refreshToken"`
	ExpiresIn    int64    `json:"expiresIn"`
	UserInfo     UserInfo `json:"userInfo"`
}

type MenuItem struct {
	Id        int64      `json:"id"`
	ParentId  int64      `json:"parentId"`
	MenuName  string     `json:"menuName"`
	MenuType  int64      `json:"menuType"`
	Path      string     `json:"path"`
	Component string     `json:"component"`
	Icon      string     `json:"icon"`
	Sort      int64      `json:"sort"`
	Perms     string     `json:"perms"`
	Status    int        `json:"status"`
	Children  []MenuItem `json:"children,optional"`
}

type UserInfo struct {
	UserId   int64      `json:"userId"`
	Username string     `json:"username"`
	Nickname string     `json:"nickname"`
	Email    string     `json:"email"`
	Phone    string     `json:"phone"`
	Avatar   string     `json:"avatar"`
	Roles    []string   `json:"roles"`
	Menus    []MenuItem `json:"menus"`
}
