// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type ApiGroupOption struct {
	Group string      `json:"group"` // 接口分组
	Apis  []ApiOption `json:"apis"`  // 分组下的接口
}

type ApiItem struct {
	Id        int64  `json:"id"`        // 接口ID
	ApiName   string `json:"apiName"`   // 接口名称
	ApiPath   string `json:"apiPath"`   // 接口路径
	Method    string `json:"method"`    // HTTP方法
	Group     string `json:"group"`     // 接口分组
	Remark    string `json:"remark"`    // 备注
	CreatedAt string `json:"createdAt"` // 创建时间
}

type ApiOption struct {
	Id      int64  `json:"id"`      // 接口ID
	ApiName string `json:"apiName"` // 接口名称
	ApiPath string `json:"apiPath"` // 接口路径,如：/api/system/user
	Method  string `json:"method"`  // HTTP方法
	Remark  string `json:"remark"`  // 角色编码
}

type CasbinRuleItem struct {
	Id       int64  `json:"id"`       // 策略ID
	Ptype    string `json:"ptype"`    // 策略类型
	RoleCode string `json:"roleCode"` // 角色编码
	ApiPath  string `json:"apiPath"`  // 接口路径
	Method   string `json:"method"`   // HTTP方法
}

type ChangePasswordReq struct {
	OldPassword string `json:"oldPassword"` // 旧密码
	NewPassword string `json:"newPassword"` // 新密码（至少8位）
}

type CreateApiReq struct {
	ApiName string `json:"apiName"`         // 接口名称
	ApiPath string `json:"apiPath"`         // 接口路径（如：/api/system/user/:id）
	Method  string `json:"method"`          // HTTP方法：GET POST PUT DELETE
	Group   string `json:"group"`           // 接口分组（如：system, plating）
	Remark  string `json:"remark,optional"` // 备注
}

type CreateDictDataReq struct {
	DictTypeId int    `json:"dictTypeId" validate:"required"` // 字典类型ID
	DictLabel  string `json:"dictLabel" validate:"required"`  // 字典标签（显示文本）
	DictValue  string `json:"dictValue" validate:"required"`  // 字典值（实际存储值）
	Sort       int    `json:"sort,optional"`                  // 排序序号
	Remark     string `json:"remark,optional"`                // 备注
	Status     int    `json:"status"`                         // 状态：1启用 0禁用
}

type CreateDictTypeReq struct {
	DictName string `json:"dictName" validate:"required"` // 字典名称
	DictCode string `json:"dictCode"`                     // 字典类型（唯一编码，如：sys_user_status）
	Remark   string `json:"remark,optional"`              // 备注
	Status   int    `json:"status"`                       // 状态：1启用 0禁用
}

type CreateMenuReq struct {
	ParentId  int64  `json:"parentId,optional"`  // 父菜单ID，顶级为0
	MenuName  string `json:"menuName"`           // 菜单名称
	MenuType  int64  `json:"menuType"`           // 菜单类型：1目录 2菜单 3按钮
	Path      string `json:"path,optional"`      // 路由路径（菜单/目录必填）
	Component string `json:"component,optional"` // 组件路径（菜单必填）
	Icon      string `json:"icon,optional"`      // 图标名称
	Sort      int    `json:"sort,optional"`      // 排序序号，越小越靠前
	Perms     string `json:"perms,optional"`     // 权限标识（如：system:user:list）
	Status    int    `json:"status"`             // 状态：1显示 0隐藏
	Visible   int    `json:"visible,optional"`   // 可见性
	Remark    string `json:"remark,optional"`
}

type CreateRoleReq struct {
	RoleName string  `json:"roleName"` // 角色名称
	RoleCode string  `json:"roleCode"` // 角色编码，唯一（如：admin, operator）
	Sort     int64   `json:"sort"`
	Remark   string  `json:"remark,optional"`  // 备注
	MenuIds  []int64 `json:"menuIds,optional"` // 关联菜单ID列表
	ApiIds   []int64 `json:"apiIds,optional"`  // 关联接口ID列表
}

type CreateUserReq struct {
	Username string  `json:"username"`          // 用户名，唯一
	Password string  `json:"password"`          // 初始密码
	Nickname string  `json:"nickname,optional"` // 昵称
	Email    string  `json:"email,optional"`    // 邮箱
	Phone    string  `json:"phone,optional"`    // 手机号
	Status   int     `json:"status"`            // 状态：1启用 0禁用
	Avatar   string  `json:"avatar,optional"`   // 头像URL
	Remark   string  `json:"remark,optional"`
	RoleIds  []int64 `json:"roleIds,optional"` // 角色ID列表
}

type DeleteUserReq struct {
	Id int64 `path:"id"` // 用户ID
}

type DictDataItem struct {
	Id        int    `json:"id"`        // 字典数据ID
	DictType  int    `json:"dictType"`  // 所属字典类型
	DictLabel string `json:"dictLabel"` // 字典标签
	DictValue string `json:"dictValue"` // 字典值
	Sort      int    `json:"sort"`      // 排序
	Remark    string `json:"remark"`    // 备注
	Status    int    `json:"status"`    // 状态
}

type DictTypeItem struct {
	Id        int    `json:"id"`        // 字典类型ID
	DictName  string `json:"dictName"`  // 字典名称
	DictCode  string `json:"dictCode"`  // 字典类型编码
	Remark    string `json:"remark"`    // 备注
	Status    int    `json:"status"`    // 状态
	CreatedAt string `json:"createdAt"` // 创建时间
}

type FileInfoResp struct {
	FileId   int64  `json:"fileId"`   // 文件ID
	FileName string `json:"fileName"` // 原始文件名
	FileURL  string `json:"fileUrl"`  // 文件访问URL
	FileSize int64  `json:"fileSize"` // 文件大小（字节）
	MimeType string `json:"mimeType"` // MIME类型
}

type GetUserReq struct {
	Id int64 `path:"id"` // 用户ID
}

type ListAllApiResp struct {
	Groups []ApiGroupOption `json:"groups"`
}

type ListAllResp struct {
	ListAll []RoleOption `list`
}

type ListApiReq struct {
	Page     int    `form:"page,default=1"`      // 页码
	PageSize int    `form:"pageSize,default=20"` // 每页数量
	Keyword  string `form:"keyword,optional"`    // 关键词（接口名/路径）
	Group    string `form:"group,optional"`      // 分组过滤
}

type ListApiResp struct {
	Total int64     `json:"total"` // 总数
	List  []ApiItem `json:"list"`  // 接口列表
}

type ListCasbinRuleReq struct {
	Page     int    `form:"page,default=1"`      // 页码
	PageSize int    `form:"pageSize,default=20"` // 每页数量
	RoleCode string `form:"roleCode,optional"`   // 角色编码
	Path     string `form:"path,optional"`       // 接口路径
	Method   string `form:"method,optional"`     // HTTP方法
}

type ListCasbinRuleResp struct {
	Total int64            `json:"total"` // 总数
	List  []CasbinRuleItem `json:"list"`  // 策略列表
}

type ListDictDataResp struct {
	Total int64          `json:"total"` // 总数
	List  []DictDataItem `json:"list"`  // 字典数据列表
}

type ListDictTypeReq struct {
	Page     int    `form:"page,default=1"`      // 页码
	PageSize int    `form:"pageSize,default=20"` // 每页数量
	Keyword  string `form:"keyword,optional"`    // 关键词
}

type ListDictTypeResp struct {
	Total int            `json:"total"` // 总数
	List  []DictTypeItem `json:"list"`  // 字典类型列表
}

type ListFileReq struct {
	Page     int    `form:"page,default=1"`      // 页码
	PageSize int    `form:"pageSize,default=20"` // 每页数量
	Keyword  string `form:"keyword,optional"`    // 文件名关键词
}

type ListFileResp struct {
	Total int64          `json:"total"` // 总数
	List  []FileInfoResp `json:"list"`  // 文件列表
}

type ListLoginLogReq struct {
	Page      int    `form:"page,default=1"`      // 页码
	PageSize  int    `form:"pageSize,default=20"` // 每页数量
	Keyword   string `json:"keyword"`             // 关键词，作用于用户名、Ip、地区
	Status    int    `form:"status,optional"`     // 状态：1成功 0失败
	StartTime string `form:"startTime,optional"`  // 开始时间（格式：2006-01-02 15:04:05）
	EndTime   string `form:"endTime,optional"`    // 结束时间
}

type ListLoginLogResp struct {
	Total int            `json:"total"` // 总数
	List  []LoginLogItem `json:"list"`  // 日志列表
}

type ListOperLogReq struct {
	Page         int    `form:"page,default=1"`      // 页码
	PageSize     int    `form:"pageSize,default=20"` // 每页数量
	Keyword      string `json:"keyword"`             // 关键词，作用于操作人、请求方式、操作IP
	BusinessType string `json:"businessType"`        // 业务类型：0=其他，1=新增，2=修改，3=删除，4=查询
	Status       int    `form:"status,optional"`     // 状态：1成功 0失败
	StartTime    string `form:"startTime,optional"`  // 开始时间
	EndTime      string `form:"endTime,optional"`    // 结束时间
}

type ListOperLogResp struct {
	Total int64         `json:"total"` // 总数
	List  []OperLogItem `json:"list"`  // 日志列表
}

type ListRoleReq struct {
	Page     int    `form:"page,default=1"`      // 页码
	PageSize int    `form:"pageSize,default=20"` // 每页数量
	Keyword  string `form:"keyword,optional"`    // 关键词
}

type ListRoleResp struct {
	Total int64      `json:"total"` // 总数
	List  []RoleItem `json:"list"`  // 角色列表
}

type ListUserReq struct {
	Page     int    `form:"page,default=1"`      // 页码
	PageSize int    `form:"pageSize,default=20"` // 每页数量
	Keyword  string `form:"keyword,optional"`    // 关键词（用户名/昵称）
	Status   *int   `form:"status,optional"`     // 状态过滤：1启用 0禁用
}

type ListUserResp struct {
	Total int64      `json:"total"` // 总数
	List  []UserItem `json:"list"`  // 用户列表
}

type LoginLogItem struct {
	Id        int    `json:"id"` // 日志ID
	UserId    int    `json:"userId"`
	Username  string `json:"username"`  // 用户名
	Ip        string `json:"ip"`        // 登录IP
	Location  string `json:"location"`  // 登录地
	UserAgent string `json:"userAgent"` // 浏览器信息
	OS        string `json:"os"`        // 操作系统
	Status    int    `json:"status"`    // 登录状态：1成功 0失败
	Msg       string `json:"msg"`       // 提示消息
	LoginTime string `json:"loginTime"` // 登录时间
}

type LoginReq struct {
	Username string `json:"username"` // 用户名
	Password string `json:"password"` // 密码（明文，传输层加密）
}

type LoginResp struct {
	AccessToken  string   `json:"accessToken"`  // 访问令牌，有效期2小时
	RefreshToken string   `json:"refreshToken"` // 刷新令牌，有效期7天
	ExpiresIn    int64    `json:"expiresIn"`    // 访问令牌剩余秒数
	UserInfo     UserInfo `json:"userInfo"`
}

type MenuItem struct {
	Id        int64      `json:"id"`                // 菜单ID
	ParentId  int64      `json:"parentId"`          // 父菜单ID
	MenuName  string     `json:"menuName"`          // 菜单名称
	MenuType  int64      `json:"menuType"`          // 菜单类型
	Path      string     `json:"path"`              // 路由路径
	Component string     `json:"component"`         // 组件路径
	Icon      string     `json:"icon"`              // 图标
	Sort      int64      `json:"sort"`              // 排序
	Perms     string     `json:"perms"`             // 权限标识
	Status    int        `json:"status"`            // 状态
	Visible   int        `json:"visible"`           // 可见性
	Children  []MenuItem `json:"children,optional"` // 子菜单列表
}

type MenuTreeResp struct {
	List []MenuItem `json:"list"` // 菜单树形列表
}

type OperLogItem struct {
	Id         int    `json:"id"`        // 日志ID
	Title      string `json:"title"`     // 操作模块标题
	OperType   string `json:"operType"`  // 操作类型（create/update/delete/query）
	Method     string `json:"method"`    // HTTP方法
	ReqMethod  string `json:"reqMethod"` // 请求方法
	OperName   string `json:"operName"`  // 操作人名称
	DeptName   string `json:"deptName"`
	ReqUrl     string `json:"reqUrl"`     // 请求URL
	ReqParam   string `json:"reqParam"`   // 请求参数
	RespResult string `json:"respResult"` // 响应结果
	Status     int    `json:"status"`     // 状态：1成功 0失败
	Ip         string `json:"ip"`         // 操作IP
	OperTime   string `json:"operTime"`   // 操作时间
}

type RefreshTokenReq struct {
	RefreshToken string `json:"refreshToken"` // 刷新令牌
}

type RefreshTokenResp struct {
	AccessToken string `json:"accessToken"` // 新访问令牌
	ExpiresIn   int64  `json:"expiresIn"`   // 新令牌有效期秒数
}

type ResetPasswordReq struct {
	Id          int64  `path:"id"`          // 用户ID
	NewPassword string `json:"newPassword"` // 新密码
}

type RoleItem struct {
	Id        int64   `json:"id"`       // 角色ID
	RoleName  string  `json:"roleName"` // 角色名称
	RoleCode  string  `json:"roleCode"` // 角色编码
	Status    int     `json:"status"`
	Sort      int     `json:sort`
	Remark    string  `json:"remark"`           // 备注
	MenuIds   []int64 `json:"menuIds,optional"` // 关联菜单ID列表
	ApiIds    []int64 `json:"apiIds,optional"`  // 关联接口ID列表
	CreatedAt string  `json:"createdAt"`        // 创建时间
}

type RoleOption struct {
	Id       int64  `json:"id"`       // 角色ID
	RoleName string `json:"roleName"` // 角色名称
	RoleCode string `json:"roleCode"` // 角色编码
}

type UpdateApiReq struct {
	Id      int64   `path:"id"`               // 接口ID
	ApiName *string `json:"apiName,optional"` // 接口名称
	ApiPath *string `json:"apiPath,optional"`
	Method  *string `json:"method,optional"`
	Group   *string `json:"group,optional"`  // 接口分组
	Remark  *string `json:"remark,optional"` // 备注
}

type UpdateDictDataReq struct {
	Id         int     `path:"id" validate:"required"`         // 字典数据ID
	DictTypeId int     `json:"dictTypeId" validate:"required"` // 字典类型ID
	DictLabel  string  `json:"dictLabel" validate:"required"`  // 字典标签
	DictValue  string  `json:"dictValue" validate:"required"`  // 字典值
	Sort       *int    `json:"sort,optional"`                  // 排序
	Remark     *string `json:"remark,optional"`                // 备注
	Status     *int    `json:"status"`                         // 状态
}

type UpdateDictTypeReq struct {
	Id       int     `path:"id" validate:"required"` // 字典类型ID
	DictName *string `json:"dictName,optional"`      // 字典名称
	DictCode *string `json:"dictCode,optional" `     // 字典类型（唯一编码，如：sys_user_status）
	Remark   *string `json:"remark,optional"`        // 备注
	Status   *int    `json:"status,optional"`        // 状态
}

type UpdateMenuReq struct {
	Id        int64   `path:"id"`                 // 菜单ID
	ParentId  *int64  `json:"parentId,optional"`  // 父菜单ID，顶级为0
	MenuName  *string `json:"menuName,optional"`  // 菜单名称
	MenuType  *int    `json:"menuType,optional"`  // 菜单类型
	Path      *string `json:"path,optional"`      // 路由路径
	Component *string `json:"component,optional"` // 组件路径
	Icon      *string `json:"icon,optional"`      // 图标
	Sort      *int    `json:"sort,optional"`      // 排序
	Perms     *string `json:"perms,optional"`     // 权限标识
	Status    *int    `json:"status,optional"`    // 菜单可用性
	Visible   *int    `json:"visible,optional"`   // 可见性
	Remark    *string `json:"remark,optional"`
}

type UpdateRolePermissionsReq struct {
	Id      int64   `path:"id"`               // 角色ID
	MenuIds []int64 `json:"menuIds,optional"` // 关联菜单ID列表
	ApiIds  []int64 `json:"apiIds,optional"`  // 关联接口ID列表
}

type UpdateRoleReq struct {
	Id       int64   `path:"id"` // 角色ID
	RoleCode *string `json:"roleCode,optional"`
	RoleName *string `json:"roleName,optional"` // 角色名称
	Sort     *int64  `json:"sort,optional"`
	Remark   *string `json:"remark,optional"` // 备注
}

type UpdateUserReq struct {
	Id       int64   `path:"id"`                // 用户ID
	Username string  `json:"username,optional"` // 用户名，唯一
	Nickname *string `json:"nickname,optional"` // 昵称
	Email    *string `json:"email,optional"`    // 邮箱
	Phone    *string `json:"phone,optional"`    // 手机号
	Status   *int    `json:"status"`            // 状态：1启用 0禁用
	Avatar   *string `json:"avatar,optional"`
	Remark   *string `json:"remark,optional"`  // 头像URL
	RoleIds  []int64 `json:"roleIds,optional"` // 角色ID列表
}

type UserInfo struct {
	UserId   int64      `json:"userId"`
	Username string     `json:"username"`
	Nickname string     `json:"nickname"`
	Email    string     `json:"email"`
	Phone    string     `json:"phone"`
	Avatar   string     `json:"avatar,optional"`
	Roles    []string   `json:"roles"`
	Menus    []MenuItem `json:"menus"`
}

type UserInfoReq struct {
}

type UserInfoResp struct {
	UserInfo UserInfo `json:"userInfo"`
}

type UserItem struct {
	Id        int64    `json:"id"`       // 用户ID
	Username  string   `json:"username"` // 用户名
	Nickname  string   `json:"nickname"` // 昵称
	Email     string   `json:"email"`    // 邮箱
	Phone     string   `json:"phone"`    // 手机号
	Status    int      `json:"status"`   // 状态
	Avatar    string   `json:"avatar"`
	Remark    string   `json:"remark"`
	Roles     []string `json:"roles"`            // 角色名称列表
	RoleIds   []int64  `json:"roleIds,optional"` // 角色ID列表
	CreatedAt string   `json:"createdAt"`        // 创建时间
	UpdatedAt string   `json:"updatedAt"`        // 更新时间
}
