// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: sys.proto

package sys

import (
	"context"

	"go-zero-rpc/sys-rpc/sys"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Sys interface {
		Login(ctx context.Context, in *sys.LoginReq, opts ...grpc.CallOption) (*sys.LoginResp, error)
	}

	defaultSys struct {
		cli zrpc.Client
	}
)

func NewSys(cli zrpc.Client) Sys {
	return &defaultSys{
		cli: cli,
	}
}

func (m *defaultSys) Login(ctx context.Context, in *sys.LoginReq, opts ...grpc.CallOption) (*sys.LoginResp, error) {
	client := sys.NewSysClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}
