// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: sys.proto

package systemservice

import (
	"context"

	"go-zero-rpc/sys-rpc/sys"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CreateUserReq    = sys.CreateUserReq
	CreateUserResp   = sys.CreateUserResp
	DeleteUserReq    = sys.DeleteUserReq
	Empty            = sys.Empty
	GetUserReq       = sys.GetUserReq
	ListUserReq      = sys.ListUserReq
	ListUserResp     = sys.ListUserResp
	ResetPasswordReq = sys.ResetPasswordReq
	UpdateUserReq    = sys.UpdateUserReq
	UserItem         = sys.UserItem

	SystemService interface {
		// 用户管理
		CreateUser(ctx context.Context, in *CreateUserReq, opts ...grpc.CallOption) (*CreateUserResp, error)
		UpdateUser(ctx context.Context, in *UpdateUserReq, opts ...grpc.CallOption) (*Empty, error)
		DeleteUser(ctx context.Context, in *DeleteUserReq, opts ...grpc.CallOption) (*Empty, error)
		GetUser(ctx context.Context, in *GetUserReq, opts ...grpc.CallOption) (*UserItem, error)
		ListUser(ctx context.Context, in *ListUserReq, opts ...grpc.CallOption) (*ListUserResp, error)
		ResetPassword(ctx context.Context, in *ResetPasswordReq, opts ...grpc.CallOption) (*Empty, error)
	}

	defaultSystemService struct {
		cli zrpc.Client
	}
)

func NewSystemService(cli zrpc.Client) SystemService {
	return &defaultSystemService{
		cli: cli,
	}
}

// 用户管理
func (m *defaultSystemService) CreateUser(ctx context.Context, in *CreateUserReq, opts ...grpc.CallOption) (*CreateUserResp, error) {
	client := sys.NewSystemServiceClient(m.cli.Conn())
	return client.CreateUser(ctx, in, opts...)
}

func (m *defaultSystemService) UpdateUser(ctx context.Context, in *UpdateUserReq, opts ...grpc.CallOption) (*Empty, error) {
	client := sys.NewSystemServiceClient(m.cli.Conn())
	return client.UpdateUser(ctx, in, opts...)
}

func (m *defaultSystemService) DeleteUser(ctx context.Context, in *DeleteUserReq, opts ...grpc.CallOption) (*Empty, error) {
	client := sys.NewSystemServiceClient(m.cli.Conn())
	return client.DeleteUser(ctx, in, opts...)
}

func (m *defaultSystemService) GetUser(ctx context.Context, in *GetUserReq, opts ...grpc.CallOption) (*UserItem, error) {
	client := sys.NewSystemServiceClient(m.cli.Conn())
	return client.GetUser(ctx, in, opts...)
}

func (m *defaultSystemService) ListUser(ctx context.Context, in *ListUserReq, opts ...grpc.CallOption) (*ListUserResp, error) {
	client := sys.NewSystemServiceClient(m.cli.Conn())
	return client.ListUser(ctx, in, opts...)
}

func (m *defaultSystemService) ResetPassword(ctx context.Context, in *ResetPasswordReq, opts ...grpc.CallOption) (*Empty, error) {
	client := sys.NewSystemServiceClient(m.cli.Conn())
	return client.ResetPassword(ctx, in, opts...)
}
