// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: sys.proto

package systemservice

import (
	"context"

	"go-zero-rpc/sys-rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ClearLoginLogReq         = pb.ClearLoginLogReq
	ClearOperLogReq          = pb.ClearOperLogReq
	CreateApiReq             = pb.CreateApiReq
	CreateApiResp            = pb.CreateApiResp
	CreateDictDataReq        = pb.CreateDictDataReq
	CreateDictDataResp       = pb.CreateDictDataResp
	CreateDictTypeReq        = pb.CreateDictTypeReq
	CreateDictTypeResp       = pb.CreateDictTypeResp
	CreateMenuReq            = pb.CreateMenuReq
	CreateMenuResp           = pb.CreateMenuResp
	CreateRoleReq            = pb.CreateRoleReq
	CreateRoleResp           = pb.CreateRoleResp
	CreateUserReq            = pb.CreateUserReq
	CreateUserResp           = pb.CreateUserResp
	DeleteApiReq             = pb.DeleteApiReq
	DeleteDictDataReq        = pb.DeleteDictDataReq
	DeleteDictTypeReq        = pb.DeleteDictTypeReq
	DeleteFileReq            = pb.DeleteFileReq
	DeleteMenuReq            = pb.DeleteMenuReq
	DeleteRoleReq            = pb.DeleteRoleReq
	DeleteUserReq            = pb.DeleteUserReq
	Empty                    = pb.Empty
	GetCurrentUserMenusReq   = pb.GetCurrentUserMenusReq
	GetDictDataByTypeReq     = pb.GetDictDataByTypeReq
	GetMenuTreeReq           = pb.GetMenuTreeReq
	GetRoleReq               = pb.GetRoleReq
	GetUserReq               = pb.GetUserReq
	ListAllApiResp           = pb.ListAllApiResp
	ListAllRoleResp          = pb.ListAllRoleResp
	ListApiReq               = pb.ListApiReq
	ListApiResp              = pb.ListApiResp
	ListCasbinRuleReq        = pb.ListCasbinRuleReq
	ListCasbinRuleResp       = pb.ListCasbinRuleResp
	ListDictDataResp         = pb.ListDictDataResp
	ListDictTypeReq          = pb.ListDictTypeReq
	ListDictTypeResp         = pb.ListDictTypeResp
	ListFileReq              = pb.ListFileReq
	ListFileResp             = pb.ListFileResp
	ListLoginLogReq          = pb.ListLoginLogReq
	ListLoginLogResp         = pb.ListLoginLogResp
	ListOperLogReq           = pb.ListOperLogReq
	ListOperLogResp          = pb.ListOperLogResp
	ListRoleReq              = pb.ListRoleReq
	ListRoleResp             = pb.ListRoleResp
	ListUserReq              = pb.ListUserReq
	ListUserResp             = pb.ListUserResp
	MenuTreeResp             = pb.MenuTreeResp
	RegisterFileReq          = pb.RegisterFileReq
	RegisterFileResp         = pb.RegisterFileResp
	ResetPasswordReq         = pb.ResetPasswordReq
	RoleItem                 = pb.RoleItem
	UpdateApiReq             = pb.UpdateApiReq
	UpdateDictDataReq        = pb.UpdateDictDataReq
	UpdateDictTypeReq        = pb.UpdateDictTypeReq
	UpdateMenuReq            = pb.UpdateMenuReq
	UpdateRolePermissionsReq = pb.UpdateRolePermissionsReq
	UpdateRoleReq            = pb.UpdateRoleReq
	UpdateUserReq            = pb.UpdateUserReq
	UserItem                 = pb.UserItem
	WriteOperLogReq          = pb.WriteOperLogReq
	WriteOperLogResp         = pb.WriteOperLogResp

	SystemService interface {
		// 用户管理
		CreateUser(ctx context.Context, in *CreateUserReq, opts ...grpc.CallOption) (*CreateUserResp, error)
		UpdateUser(ctx context.Context, in *UpdateUserReq, opts ...grpc.CallOption) (*Empty, error)
		DeleteUser(ctx context.Context, in *DeleteUserReq, opts ...grpc.CallOption) (*Empty, error)
		GetUser(ctx context.Context, in *GetUserReq, opts ...grpc.CallOption) (*UserItem, error)
		ListUser(ctx context.Context, in *ListUserReq, opts ...grpc.CallOption) (*ListUserResp, error)
		ResetPassword(ctx context.Context, in *ResetPasswordReq, opts ...grpc.CallOption) (*Empty, error)
		// 角色管理
		CreateRole(ctx context.Context, in *CreateRoleReq, opts ...grpc.CallOption) (*CreateRoleResp, error)
		UpdateRole(ctx context.Context, in *UpdateRoleReq, opts ...grpc.CallOption) (*Empty, error)
		UpdateRolePermissions(ctx context.Context, in *UpdateRolePermissionsReq, opts ...grpc.CallOption) (*Empty, error)
		DeleteRole(ctx context.Context, in *DeleteRoleReq, opts ...grpc.CallOption) (*Empty, error)
		GetRole(ctx context.Context, in *GetRoleReq, opts ...grpc.CallOption) (*RoleItem, error)
		ListRole(ctx context.Context, in *ListRoleReq, opts ...grpc.CallOption) (*ListRoleResp, error)
		ListAllRole(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListAllRoleResp, error)
		// 菜单管理
		CreateMenu(ctx context.Context, in *CreateMenuReq, opts ...grpc.CallOption) (*CreateMenuResp, error)
		UpdateMenu(ctx context.Context, in *UpdateMenuReq, opts ...grpc.CallOption) (*Empty, error)
		DeleteMenu(ctx context.Context, in *DeleteMenuReq, opts ...grpc.CallOption) (*Empty, error)
		GetMenuTree(ctx context.Context, in *GetMenuTreeReq, opts ...grpc.CallOption) (*MenuTreeResp, error)
		GetCurrentUserMenus(ctx context.Context, in *GetCurrentUserMenusReq, opts ...grpc.CallOption) (*MenuTreeResp, error)
		// API 接口管理
		CreateApi(ctx context.Context, in *CreateApiReq, opts ...grpc.CallOption) (*CreateApiResp, error)
		UpdateApi(ctx context.Context, in *UpdateApiReq, opts ...grpc.CallOption) (*Empty, error)
		DeleteApi(ctx context.Context, in *DeleteApiReq, opts ...grpc.CallOption) (*Empty, error)
		ListApi(ctx context.Context, in *ListApiReq, opts ...grpc.CallOption) (*ListApiResp, error)
		ListAllApi(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListAllApiResp, error)
		ListCasbinRule(ctx context.Context, in *ListCasbinRuleReq, opts ...grpc.CallOption) (*ListCasbinRuleResp, error)
		// 字典管理
		CreateDictType(ctx context.Context, in *CreateDictTypeReq, opts ...grpc.CallOption) (*CreateDictTypeResp, error)
		UpdateDictType(ctx context.Context, in *UpdateDictTypeReq, opts ...grpc.CallOption) (*Empty, error)
		DeleteDictType(ctx context.Context, in *DeleteDictTypeReq, opts ...grpc.CallOption) (*Empty, error)
		ListDictType(ctx context.Context, in *ListDictTypeReq, opts ...grpc.CallOption) (*ListDictTypeResp, error)
		CreateDictData(ctx context.Context, in *CreateDictDataReq, opts ...grpc.CallOption) (*CreateDictDataResp, error)
		UpdateDictData(ctx context.Context, in *UpdateDictDataReq, opts ...grpc.CallOption) (*Empty, error)
		DeleteDictData(ctx context.Context, in *DeleteDictDataReq, opts ...grpc.CallOption) (*Empty, error)
		GetDictDataByType(ctx context.Context, in *GetDictDataByTypeReq, opts ...grpc.CallOption) (*ListDictDataResp, error)
		// 日志管理
		ListLoginLog(ctx context.Context, in *ListLoginLogReq, opts ...grpc.CallOption) (*ListLoginLogResp, error)
		ClearLoginLog(ctx context.Context, in *ClearLoginLogReq, opts ...grpc.CallOption) (*Empty, error)
		ListOperLog(ctx context.Context, in *ListOperLogReq, opts ...grpc.CallOption) (*ListOperLogResp, error)
		ClearOperLog(ctx context.Context, in *ClearOperLogReq, opts ...grpc.CallOption) (*Empty, error)
		WriteOperLog(ctx context.Context, in *WriteOperLogReq, opts ...grpc.CallOption) (*WriteOperLogResp, error)
		// 文件管理（待启用）
		RegisterFile(ctx context.Context, in *RegisterFileReq, opts ...grpc.CallOption) (*RegisterFileResp, error)
		DeleteFile(ctx context.Context, in *DeleteFileReq, opts ...grpc.CallOption) (*Empty, error)
		ListFile(ctx context.Context, in *ListFileReq, opts ...grpc.CallOption) (*ListFileResp, error)
	}

	defaultSystemService struct {
		cli zrpc.Client
	}
)

func NewSystemService(cli zrpc.Client) SystemService {
	return &defaultSystemService{
		cli: cli,
	}
}

// 用户管理
func (m *defaultSystemService) CreateUser(ctx context.Context, in *CreateUserReq, opts ...grpc.CallOption) (*CreateUserResp, error) {
	client := pb.NewSystemServiceClient(m.cli.Conn())
	return client.CreateUser(ctx, in, opts...)
}

func (m *defaultSystemService) UpdateUser(ctx context.Context, in *UpdateUserReq, opts ...grpc.CallOption) (*Empty, error) {
	client := pb.NewSystemServiceClient(m.cli.Conn())
	return client.UpdateUser(ctx, in, opts...)
}

func (m *defaultSystemService) DeleteUser(ctx context.Context, in *DeleteUserReq, opts ...grpc.CallOption) (*Empty, error) {
	client := pb.NewSystemServiceClient(m.cli.Conn())
	return client.DeleteUser(ctx, in, opts...)
}

func (m *defaultSystemService) GetUser(ctx context.Context, in *GetUserReq, opts ...grpc.CallOption) (*UserItem, error) {
	client := pb.NewSystemServiceClient(m.cli.Conn())
	return client.GetUser(ctx, in, opts...)
}

func (m *defaultSystemService) ListUser(ctx context.Context, in *ListUserReq, opts ...grpc.CallOption) (*ListUserResp, error) {
	client := pb.NewSystemServiceClient(m.cli.Conn())
	return client.ListUser(ctx, in, opts...)
}

func (m *defaultSystemService) ResetPassword(ctx context.Context, in *ResetPasswordReq, opts ...grpc.CallOption) (*Empty, error) {
	client := pb.NewSystemServiceClient(m.cli.Conn())
	return client.ResetPassword(ctx, in, opts...)
}

// 角色管理
func (m *defaultSystemService) CreateRole(ctx context.Context, in *CreateRoleReq, opts ...grpc.CallOption) (*CreateRoleResp, error) {
	client := pb.NewSystemServiceClient(m.cli.Conn())
	return client.CreateRole(ctx, in, opts...)
}

func (m *defaultSystemService) UpdateRole(ctx context.Context, in *UpdateRoleReq, opts ...grpc.CallOption) (*Empty, error) {
	client := pb.NewSystemServiceClient(m.cli.Conn())
	return client.UpdateRole(ctx, in, opts...)
}

func (m *defaultSystemService) UpdateRolePermissions(ctx context.Context, in *UpdateRolePermissionsReq, opts ...grpc.CallOption) (*Empty, error) {
	client := pb.NewSystemServiceClient(m.cli.Conn())
	return client.UpdateRolePermissions(ctx, in, opts...)
}

func (m *defaultSystemService) DeleteRole(ctx context.Context, in *DeleteRoleReq, opts ...grpc.CallOption) (*Empty, error) {
	client := pb.NewSystemServiceClient(m.cli.Conn())
	return client.DeleteRole(ctx, in, opts...)
}

func (m *defaultSystemService) GetRole(ctx context.Context, in *GetRoleReq, opts ...grpc.CallOption) (*RoleItem, error) {
	client := pb.NewSystemServiceClient(m.cli.Conn())
	return client.GetRole(ctx, in, opts...)
}

func (m *defaultSystemService) ListRole(ctx context.Context, in *ListRoleReq, opts ...grpc.CallOption) (*ListRoleResp, error) {
	client := pb.NewSystemServiceClient(m.cli.Conn())
	return client.ListRole(ctx, in, opts...)
}

func (m *defaultSystemService) ListAllRole(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListAllRoleResp, error) {
	client := pb.NewSystemServiceClient(m.cli.Conn())
	return client.ListAllRole(ctx, in, opts...)
}

// 菜单管理
func (m *defaultSystemService) CreateMenu(ctx context.Context, in *CreateMenuReq, opts ...grpc.CallOption) (*CreateMenuResp, error) {
	client := pb.NewSystemServiceClient(m.cli.Conn())
	return client.CreateMenu(ctx, in, opts...)
}

func (m *defaultSystemService) UpdateMenu(ctx context.Context, in *UpdateMenuReq, opts ...grpc.CallOption) (*Empty, error) {
	client := pb.NewSystemServiceClient(m.cli.Conn())
	return client.UpdateMenu(ctx, in, opts...)
}

func (m *defaultSystemService) DeleteMenu(ctx context.Context, in *DeleteMenuReq, opts ...grpc.CallOption) (*Empty, error) {
	client := pb.NewSystemServiceClient(m.cli.Conn())
	return client.DeleteMenu(ctx, in, opts...)
}

func (m *defaultSystemService) GetMenuTree(ctx context.Context, in *GetMenuTreeReq, opts ...grpc.CallOption) (*MenuTreeResp, error) {
	client := pb.NewSystemServiceClient(m.cli.Conn())
	return client.GetMenuTree(ctx, in, opts...)
}

func (m *defaultSystemService) GetCurrentUserMenus(ctx context.Context, in *GetCurrentUserMenusReq, opts ...grpc.CallOption) (*MenuTreeResp, error) {
	client := pb.NewSystemServiceClient(m.cli.Conn())
	return client.GetCurrentUserMenus(ctx, in, opts...)
}

// API 接口管理
func (m *defaultSystemService) CreateApi(ctx context.Context, in *CreateApiReq, opts ...grpc.CallOption) (*CreateApiResp, error) {
	client := pb.NewSystemServiceClient(m.cli.Conn())
	return client.CreateApi(ctx, in, opts...)
}

func (m *defaultSystemService) UpdateApi(ctx context.Context, in *UpdateApiReq, opts ...grpc.CallOption) (*Empty, error) {
	client := pb.NewSystemServiceClient(m.cli.Conn())
	return client.UpdateApi(ctx, in, opts...)
}

func (m *defaultSystemService) DeleteApi(ctx context.Context, in *DeleteApiReq, opts ...grpc.CallOption) (*Empty, error) {
	client := pb.NewSystemServiceClient(m.cli.Conn())
	return client.DeleteApi(ctx, in, opts...)
}

func (m *defaultSystemService) ListApi(ctx context.Context, in *ListApiReq, opts ...grpc.CallOption) (*ListApiResp, error) {
	client := pb.NewSystemServiceClient(m.cli.Conn())
	return client.ListApi(ctx, in, opts...)
}

func (m *defaultSystemService) ListAllApi(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListAllApiResp, error) {
	client := pb.NewSystemServiceClient(m.cli.Conn())
	return client.ListAllApi(ctx, in, opts...)
}

func (m *defaultSystemService) ListCasbinRule(ctx context.Context, in *ListCasbinRuleReq, opts ...grpc.CallOption) (*ListCasbinRuleResp, error) {
	client := pb.NewSystemServiceClient(m.cli.Conn())
	return client.ListCasbinRule(ctx, in, opts...)
}

// 字典管理
func (m *defaultSystemService) CreateDictType(ctx context.Context, in *CreateDictTypeReq, opts ...grpc.CallOption) (*CreateDictTypeResp, error) {
	client := pb.NewSystemServiceClient(m.cli.Conn())
	return client.CreateDictType(ctx, in, opts...)
}

func (m *defaultSystemService) UpdateDictType(ctx context.Context, in *UpdateDictTypeReq, opts ...grpc.CallOption) (*Empty, error) {
	client := pb.NewSystemServiceClient(m.cli.Conn())
	return client.UpdateDictType(ctx, in, opts...)
}

func (m *defaultSystemService) DeleteDictType(ctx context.Context, in *DeleteDictTypeReq, opts ...grpc.CallOption) (*Empty, error) {
	client := pb.NewSystemServiceClient(m.cli.Conn())
	return client.DeleteDictType(ctx, in, opts...)
}

func (m *defaultSystemService) ListDictType(ctx context.Context, in *ListDictTypeReq, opts ...grpc.CallOption) (*ListDictTypeResp, error) {
	client := pb.NewSystemServiceClient(m.cli.Conn())
	return client.ListDictType(ctx, in, opts...)
}

func (m *defaultSystemService) CreateDictData(ctx context.Context, in *CreateDictDataReq, opts ...grpc.CallOption) (*CreateDictDataResp, error) {
	client := pb.NewSystemServiceClient(m.cli.Conn())
	return client.CreateDictData(ctx, in, opts...)
}

func (m *defaultSystemService) UpdateDictData(ctx context.Context, in *UpdateDictDataReq, opts ...grpc.CallOption) (*Empty, error) {
	client := pb.NewSystemServiceClient(m.cli.Conn())
	return client.UpdateDictData(ctx, in, opts...)
}

func (m *defaultSystemService) DeleteDictData(ctx context.Context, in *DeleteDictDataReq, opts ...grpc.CallOption) (*Empty, error) {
	client := pb.NewSystemServiceClient(m.cli.Conn())
	return client.DeleteDictData(ctx, in, opts...)
}

func (m *defaultSystemService) GetDictDataByType(ctx context.Context, in *GetDictDataByTypeReq, opts ...grpc.CallOption) (*ListDictDataResp, error) {
	client := pb.NewSystemServiceClient(m.cli.Conn())
	return client.GetDictDataByType(ctx, in, opts...)
}

// 日志管理
func (m *defaultSystemService) ListLoginLog(ctx context.Context, in *ListLoginLogReq, opts ...grpc.CallOption) (*ListLoginLogResp, error) {
	client := pb.NewSystemServiceClient(m.cli.Conn())
	return client.ListLoginLog(ctx, in, opts...)
}

func (m *defaultSystemService) ClearLoginLog(ctx context.Context, in *ClearLoginLogReq, opts ...grpc.CallOption) (*Empty, error) {
	client := pb.NewSystemServiceClient(m.cli.Conn())
	return client.ClearLoginLog(ctx, in, opts...)
}

func (m *defaultSystemService) ListOperLog(ctx context.Context, in *ListOperLogReq, opts ...grpc.CallOption) (*ListOperLogResp, error) {
	client := pb.NewSystemServiceClient(m.cli.Conn())
	return client.ListOperLog(ctx, in, opts...)
}

func (m *defaultSystemService) ClearOperLog(ctx context.Context, in *ClearOperLogReq, opts ...grpc.CallOption) (*Empty, error) {
	client := pb.NewSystemServiceClient(m.cli.Conn())
	return client.ClearOperLog(ctx, in, opts...)
}

func (m *defaultSystemService) WriteOperLog(ctx context.Context, in *WriteOperLogReq, opts ...grpc.CallOption) (*WriteOperLogResp, error) {
	client := pb.NewSystemServiceClient(m.cli.Conn())
	return client.WriteOperLog(ctx, in, opts...)
}

// 文件管理（待启用）
func (m *defaultSystemService) RegisterFile(ctx context.Context, in *RegisterFileReq, opts ...grpc.CallOption) (*RegisterFileResp, error) {
	client := pb.NewSystemServiceClient(m.cli.Conn())
	return client.RegisterFile(ctx, in, opts...)
}

func (m *defaultSystemService) DeleteFile(ctx context.Context, in *DeleteFileReq, opts ...grpc.CallOption) (*Empty, error) {
	client := pb.NewSystemServiceClient(m.cli.Conn())
	return client.DeleteFile(ctx, in, opts...)
}

func (m *defaultSystemService) ListFile(ctx context.Context, in *ListFileReq, opts ...grpc.CallOption) (*ListFileResp, error) {
	client := pb.NewSystemServiceClient(m.cli.Conn())
	return client.ListFile(ctx, in, opts...)
}
