// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: sys.proto

package server

import (
	"context"

	"go-zero-rpc/sys-rpc/internal/logic/authservice"
	"go-zero-rpc/sys-rpc/internal/svc"
	"go-zero-rpc/sys-rpc/pb"
)

type AuthServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedAuthServiceServer
}

func NewAuthServiceServer(svcCtx *svc.ServiceContext) *AuthServiceServer {
	return &AuthServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *AuthServiceServer) Login(ctx context.Context, in *pb.LoginReq) (*pb.LoginResp, error) {
	l := authservicelogic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *AuthServiceServer) RefreshToken(ctx context.Context, in *pb.RefreshTokenReq) (*pb.RefreshTokenResp, error) {
	l := authservicelogic.NewRefreshTokenLogic(ctx, s.svcCtx)
	return l.RefreshToken(in)
}

func (s *AuthServiceServer) Logout(ctx context.Context, in *pb.LogoutReq) (*pb.CommonResp, error) {
	l := authservicelogic.NewLogoutLogic(ctx, s.svcCtx)
	return l.Logout(in)
}

func (s *AuthServiceServer) ChangePassword(ctx context.Context, in *pb.ChangePasswordReq) (*pb.CommonResp, error) {
	l := authservicelogic.NewChangePasswordLogic(ctx, s.svcCtx)
	return l.ChangePassword(in)
}

func (s *AuthServiceServer) GetCurrentUser(ctx context.Context, in *pb.GetCurrentUserReq) (*pb.GetCurrentUserResp, error) {
	l := authservicelogic.NewGetCurrentUserLogic(ctx, s.svcCtx)
	return l.GetCurrentUser(in)
}
