// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: sys.proto

package authservice

import (
	"context"

	"go-zero-rpc/sys-rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ChangePasswordReq  = pb.ChangePasswordReq
	CommonResp         = pb.CommonResp
	GetCurrentUserReq  = pb.GetCurrentUserReq
	GetCurrentUserResp = pb.GetCurrentUserResp
	LoginReq           = pb.LoginReq
	LoginResp          = pb.LoginResp
	LogoutReq          = pb.LogoutReq
	RefreshTokenReq    = pb.RefreshTokenReq
	RefreshTokenResp   = pb.RefreshTokenResp

	AuthService interface {
		Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error)
		RefreshToken(ctx context.Context, in *RefreshTokenReq, opts ...grpc.CallOption) (*RefreshTokenResp, error)
		Logout(ctx context.Context, in *LogoutReq, opts ...grpc.CallOption) (*CommonResp, error)
		ChangePassword(ctx context.Context, in *ChangePasswordReq, opts ...grpc.CallOption) (*CommonResp, error)
		GetCurrentUser(ctx context.Context, in *GetCurrentUserReq, opts ...grpc.CallOption) (*GetCurrentUserResp, error)
	}

	defaultAuthService struct {
		cli zrpc.Client
	}
)

func NewAuthService(cli zrpc.Client) AuthService {
	return &defaultAuthService{
		cli: cli,
	}
}

func (m *defaultAuthService) Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error) {
	client := pb.NewAuthServiceClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}

func (m *defaultAuthService) RefreshToken(ctx context.Context, in *RefreshTokenReq, opts ...grpc.CallOption) (*RefreshTokenResp, error) {
	client := pb.NewAuthServiceClient(m.cli.Conn())
	return client.RefreshToken(ctx, in, opts...)
}

func (m *defaultAuthService) Logout(ctx context.Context, in *LogoutReq, opts ...grpc.CallOption) (*CommonResp, error) {
	client := pb.NewAuthServiceClient(m.cli.Conn())
	return client.Logout(ctx, in, opts...)
}

func (m *defaultAuthService) ChangePassword(ctx context.Context, in *ChangePasswordReq, opts ...grpc.CallOption) (*CommonResp, error) {
	client := pb.NewAuthServiceClient(m.cli.Conn())
	return client.ChangePassword(ctx, in, opts...)
}

func (m *defaultAuthService) GetCurrentUser(ctx context.Context, in *GetCurrentUserReq, opts ...grpc.CallOption) (*GetCurrentUserResp, error) {
	client := pb.NewAuthServiceClient(m.cli.Conn())
	return client.GetCurrentUser(ctx, in, opts...)
}
