// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: sys.proto

package permissionservice

import (
	"context"

	"go-zero-rpc/sys-rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CheckPermissionReq   = pb.CheckPermissionReq
	CheckPermissionResp  = pb.CheckPermissionResp
	GetRolesByUserIdReq  = pb.GetRolesByUserIdReq
	GetRolesByUserIdResp = pb.GetRolesByUserIdResp
	GetUserByIdReq       = pb.GetUserByIdReq
	GetUserByIdResp      = pb.GetUserByIdResp
	IsBlackListReq       = pb.IsBlackListReq
	IsBlackListResp      = pb.IsBlackListResp

	PermissionService interface {
		CheckPermission(ctx context.Context, in *CheckPermissionReq, opts ...grpc.CallOption) (*CheckPermissionResp, error)
		GetUserById(ctx context.Context, in *GetUserByIdReq, opts ...grpc.CallOption) (*GetUserByIdResp, error)
		GetRolesByUserId(ctx context.Context, in *GetRolesByUserIdReq, opts ...grpc.CallOption) (*GetRolesByUserIdResp, error)
		IsTokenRevoked(ctx context.Context, in *IsBlackListReq, opts ...grpc.CallOption) (*IsBlackListResp, error)
	}

	defaultPermissionService struct {
		cli zrpc.Client
	}
)

func NewPermissionService(cli zrpc.Client) PermissionService {
	return &defaultPermissionService{
		cli: cli,
	}
}

func (m *defaultPermissionService) CheckPermission(ctx context.Context, in *CheckPermissionReq, opts ...grpc.CallOption) (*CheckPermissionResp, error) {
	client := pb.NewPermissionServiceClient(m.cli.Conn())
	return client.CheckPermission(ctx, in, opts...)
}

func (m *defaultPermissionService) GetUserById(ctx context.Context, in *GetUserByIdReq, opts ...grpc.CallOption) (*GetUserByIdResp, error) {
	client := pb.NewPermissionServiceClient(m.cli.Conn())
	return client.GetUserById(ctx, in, opts...)
}

func (m *defaultPermissionService) GetRolesByUserId(ctx context.Context, in *GetRolesByUserIdReq, opts ...grpc.CallOption) (*GetRolesByUserIdResp, error) {
	client := pb.NewPermissionServiceClient(m.cli.Conn())
	return client.GetRolesByUserId(ctx, in, opts...)
}

func (m *defaultPermissionService) IsTokenRevoked(ctx context.Context, in *IsBlackListReq, opts ...grpc.CallOption) (*IsBlackListResp, error) {
	client := pb.NewPermissionServiceClient(m.cli.Conn())
	return client.IsTokenRevoked(ctx, in, opts...)
}
